### ISSUE TITLE
Missing ST7735.h

### ISSUE THREAD

**Issue by rgwynnjones** [SnrNotHere16/ArcadeStickWithScreen#1]
Hi, Nice project.
I wanted to build this as an example of a CCS project using Git.
Found there are no CCS project files in the repo - no problem I created a new project and added the Tivaware headers to resolve some missing header problems.
But no ST7735.h to be found in the repo and not surprisingly in the TI directories.
Could you add it to you repo or should others collect this from ST?
Would be nice to have project setup and build comments in the readme.

**Comment by SnrNotHere16** [comment]
Hi, thanks for the feedback. I just added the ST7735.h header and c file. In addition to any other necessary files.  If anything else is needed please let me know. However, I am unfamiliar with how to make a project convenient for setup so bear with me. Thank you.  If you just want to setup the project, I can post the bin file and it can be loaded onto the tm4c via LM flash programmer. Would that be more convenient?
