### ISSUE TITLE
Errors in startup.ccs.c and usb_dev_gamepad.c when compiling

### ISSUE THREAD

**Issue by BloatedKidneys** [SnrNotHere16/ArcadeStickWithScreen#3]
Hello! 
I'm using this project as a base for a project of my own, and it feels like I'm missing a .h file or something. 
When compiling I'm given a list of errors, some for startup.ccs.c, and a pile for usb_dev_gamepad.c. 
Attached is a photo of my error printout, any clue as to what I'm doing wrong? 
Thanks for your help!
![Screenshot 2022-02-15 173906](https://user-images.githubusercontent.com/99765137/154153754-ffa87000-e234-4e93-8046-95c70fdfe6b2.png)

**Comment by SnrNotHere16** [comment]
Hello, sorry for the late reply. I have had a lot going on, to address your issue. Unfortunately, I cannot solve your problem. I can't add my whole project. Though I am redoing this project without the the screen and adding an additional button as well as changing some ports on another repository. On that repository, I show how to import the starter project from CCS, which I modified. When I have more time, I will show what files need to be changed from the starter project to have my project working. If I recall correctly, only buttons.c, buttons.h, and usb_dev_gamepad.c need to be changed. On the other repository, I added the whole folder of the starter project but I don't know if you will run into the same issue when trying to run it. 
https://github.com/SnrNotHere16/ArcadeStickWithoutScreen
Best.
